name:          unifmt
version:       0.2.11
author:        Herman Bergwerf <hermanbergwerf@gmail.com>
description:   A universal code formatter.
homepage:      https://github.com/hermanbergwerf/unifmt
executables:
  unifmt:      unifmt
environment:
  sdk:         '>=1.8.0 <2.0.0'
dependencies:
  args:        ^0.13.2
  glob:        ^1.0.5
  which:       ^0.1.3
  watcher:     ^0.9.7
